import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import HomeImg from "../public/home.svg";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stopify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-[80vw] xl:max-w-[50vw] flex flex-col gap-8 sm:flex-row">
        <div className="flex-3">
          <Image width={400} height={400} src={HomeImg} alt="" />
        </div>
        <div className="flex-1">
          <h1 className="text-5xl font-black">
            Share Your Love for <span className="text-green-400">Music</span>{" "}
            With Friends.
          </h1>
          <p className="hidden md:block mt-4 sm:text-sm lg:text-lg">
            STOPIFY is a social platform that allows you to keep track of all
            the music you listen to and grow your passion for music with
            friends. Write reviews, rate albums, and compile lists in music's
            fastest growing community.
          </p>
        </div>
      </div>
    </div>
  );
};

export default Home;
